export enum QueryKeys {
  LISTINGS = 'LISTINGS',
  WHO_AM_I = 'WHO_AM_I',
  STATES = 'STATES',
  PROPERTIES_ANALYTICS = 'PROPERTIES_ANALYTICS',
  PROPERTIES_FILTERING = 'PROPERTIES_FILTERING',
  COMPANY = 'COMPANY',
  PRODUCTS = 'PRODUCTS',
  SUBSCRIPTIONS = 'SUBSCRIPTIONS',
  ACTIVE_SUBSCRIPTIONS_STATES = 'ACTIVE_SUBSCRIPTIONS_STATES',
}
