export enum QueryKeys {
  LISTINGS = 'LISTINGS',
  WHO_AM_I = 'WHO_AM_I',
  STATES = 'STATES',
  PROPERTIES_ANALYTICS = 'PROPERTIES_ANALYTICS',
  PROPERTIES_FILTERING = 'PROPERTIES_FILTERING',
  COMPANY = 'COMPANY',
  PRODUCTS = 'PRODUCTS',
}
